name: CI

on:
  workflow_call:
    inputs:
      build-ref:
        required: true
        type: string
  workflow_dispatch:
  push:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4

    - run: dotnet restore /p:ContinuousIntegrationBuild=true
    - run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true

    - run: >
        dotnet test
        -c Release --no-restore --no-build
        /p:ContinuousIntegrationBuild=true
        /bl:artifacts/test.binlog --diag:artifacts/testdiag.txt
        --collect:"XPlat Code Coverage"

    - uses: actions/upload-artifact@v4
      with:
        name: logs
        path: artifacts/**/*
